webtalk_init -webtalk_dir C:\\Users\\erick.medina\\Documents\\ESDC\\esdc\\lab1\\hardware\\lab1.sdk\\webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "vie sep 28 12:48:01 2018" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2014.3" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2014.3" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "175202792_200816021_210573755_848" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "ugfbk0ler9qj9reqq9tmv96n9k" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2014.3_2" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "2" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 7 , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Service Pack 1  (build 7601)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-3470 CPU @ 3.20GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3192 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "4.000 GB" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1538130337417" -context "sdk\\\\hardware/1538130337417"
webtalk_add_data -client sdk -key isZynq -value "true" -context "sdk\\\\hardware/1538130337417"
webtalk_add_data -client sdk -key Processors -value "2" -context "sdk\\\\hardware/1538130337417"
webtalk_add_data -client sdk -key VivadoVersion -value "2014.3.1" -context "sdk\\\\hardware/1538130337417"
webtalk_add_data -client sdk -key Arch -value "zynq" -context "sdk\\\\hardware/1538130337417"
webtalk_add_data -client sdk -key Device -value "7z010" -context "sdk\\\\hardware/1538130337417"
webtalk_add_data -client sdk -key IsHandoff -value "true" -context "sdk\\\\hardware/1538130337417"
webtalk_add_data -client sdk -key uid -value "1538130575391" -context "sdk\\\\bsp/1538130575391"
webtalk_add_data -client sdk -key hwid -value "1538130337417" -context "sdk\\\\bsp/1538130575391"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\bsp/1538130575391"
webtalk_add_data -client sdk -key apptemplate -value "hello_world" -context "sdk\\\\bsp/1538130575391"
webtalk_add_data -client sdk -key uid -value "1538130584316" -context "sdk\\\\application/1538130584316"
webtalk_add_data -client sdk -key hwid -value "1538130337417" -context "sdk\\\\application/1538130584316"
webtalk_add_data -client sdk -key bspid -value "1538130575391" -context "sdk\\\\application/1538130584316"
webtalk_add_data -client sdk -key newbsp -value "true" -context "sdk\\\\application/1538130584316"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\application/1538130584316"
webtalk_add_data -client sdk -key apptemplate -value "hello_world" -context "sdk\\\\application/1538130584316"
webtalk_transmit -clientid 1837162855 -regid "175202792_200816021_210573755_848" -xml C:\\Users\\erick.medina\\Documents\\ESDC\\esdc\\lab1\\hardware\\lab1.sdk\\webtalk\\usage_statistics_ext_sdk.xml -html C:\\Users\\erick.medina\\Documents\\ESDC\\esdc\\lab1\\hardware\\lab1.sdk\\webtalk\\usage_statistics_ext_sdk.html -wdm C:\\Users\\erick.medina\\Documents\\ESDC\\esdc\\lab1\\hardware\\lab1.sdk\\webtalk\\sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
