# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/LAB2/zyboVGA.xdc

# Block Designs: bd/design_1/design_1.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1}]

# IP: bd/design_1/ip/design_1_comparator_0_0/design_1_comparator_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_comparator_0_0 || ORIG_REF_NAME==design_1_comparator_0_0}]

# IP: bd/design_1/ip/design_1_session3_0_0/design_1_session3_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_session3_0_0 || ORIG_REF_NAME==design_1_session3_0_0}]

# IP: bd/design_1/ip/design_1_f_div5_0_0/design_1_f_div5_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_f_div5_0_0 || ORIG_REF_NAME==design_1_f_div5_0_0}]

# IP: bd/design_1/ip/design_1_VGA_SYNC_0_1/design_1_VGA_SYNC_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_VGA_SYNC_0_1 || ORIG_REF_NAME==design_1_VGA_SYNC_0_1}]

# XDC: bd/design_1/design_1_ooc.xdc
