# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/hardware_lab0/hardware_lab0.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hardware_lab0 || ORIG_REF_NAME==hardware_lab0}]

# IP: bd/hardware_lab0/ip/hardware_lab0_processing_system7_0_0/hardware_lab0_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hardware_lab0_processing_system7_0_0 || ORIG_REF_NAME==hardware_lab0_processing_system7_0_0}]

# IP: bd/hardware_lab0/ip/hardware_lab0_axi_gpio_1_0/hardware_lab0_axi_gpio_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hardware_lab0_axi_gpio_1_0 || ORIG_REF_NAME==hardware_lab0_axi_gpio_1_0}]

# IP: bd/hardware_lab0/ip/hardware_lab0_axi_gpio_2_0/hardware_lab0_axi_gpio_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hardware_lab0_axi_gpio_2_0 || ORIG_REF_NAME==hardware_lab0_axi_gpio_2_0}]

# IP: bd/hardware_lab0/ip/hardware_lab0_axi_gpio_0_1/hardware_lab0_axi_gpio_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hardware_lab0_axi_gpio_0_1 || ORIG_REF_NAME==hardware_lab0_axi_gpio_0_1}]

# IP: bd/hardware_lab0/ip/hardware_lab0_processing_system7_0_axi_periph_1/hardware_lab0_processing_system7_0_axi_periph_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hardware_lab0_processing_system7_0_axi_periph_1 || ORIG_REF_NAME==hardware_lab0_processing_system7_0_axi_periph_1}]

# IP: bd/hardware_lab0/ip/hardware_lab0_rst_processing_system7_0_100M_1/hardware_lab0_rst_processing_system7_0_100M_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hardware_lab0_rst_processing_system7_0_100M_1 || ORIG_REF_NAME==hardware_lab0_rst_processing_system7_0_100M_1}]

# IP: bd/hardware_lab0/ip/hardware_lab0_xbar_1/hardware_lab0_xbar_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hardware_lab0_xbar_1 || ORIG_REF_NAME==hardware_lab0_xbar_1}]

# IP: bd/hardware_lab0/ip/hardware_lab0_auto_pc_0/hardware_lab0_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hardware_lab0_auto_pc_0 || ORIG_REF_NAME==hardware_lab0_auto_pc_0}]

# XDC: bd/hardware_lab0/ip/hardware_lab0_processing_system7_0_0/hardware_lab0_processing_system7_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==hardware_lab0_processing_system7_0_0 || ORIG_REF_NAME==hardware_lab0_processing_system7_0_0}] {/inst }]/inst ]]

# XDC: bd/hardware_lab0/ip/hardware_lab0_axi_gpio_1_0/hardware_lab0_axi_gpio_1_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==hardware_lab0_axi_gpio_1_0 || ORIG_REF_NAME==hardware_lab0_axi_gpio_1_0}] {/U0 }]/U0 ]]

# XDC: bd/hardware_lab0/ip/hardware_lab0_axi_gpio_1_0/hardware_lab0_axi_gpio_1_0_ooc.xdc

# XDC: bd/hardware_lab0/ip/hardware_lab0_axi_gpio_1_0/hardware_lab0_axi_gpio_1_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==hardware_lab0_axi_gpio_1_0 || ORIG_REF_NAME==hardware_lab0_axi_gpio_1_0}] {/U0 }]/U0 ]]

# XDC: bd/hardware_lab0/ip/hardware_lab0_axi_gpio_2_0/hardware_lab0_axi_gpio_2_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==hardware_lab0_axi_gpio_2_0 || ORIG_REF_NAME==hardware_lab0_axi_gpio_2_0}] {/U0 }]/U0 ]]

# XDC: bd/hardware_lab0/ip/hardware_lab0_axi_gpio_2_0/hardware_lab0_axi_gpio_2_0_ooc.xdc

# XDC: bd/hardware_lab0/ip/hardware_lab0_axi_gpio_2_0/hardware_lab0_axi_gpio_2_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==hardware_lab0_axi_gpio_2_0 || ORIG_REF_NAME==hardware_lab0_axi_gpio_2_0}] {/U0 }]/U0 ]]

# XDC: bd/hardware_lab0/ip/hardware_lab0_axi_gpio_0_1/hardware_lab0_axi_gpio_0_1_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==hardware_lab0_axi_gpio_0_1 || ORIG_REF_NAME==hardware_lab0_axi_gpio_0_1}] {/U0 }]/U0 ]]

# XDC: bd/hardware_lab0/ip/hardware_lab0_axi_gpio_0_1/hardware_lab0_axi_gpio_0_1_ooc.xdc

# XDC: bd/hardware_lab0/ip/hardware_lab0_axi_gpio_0_1/hardware_lab0_axi_gpio_0_1.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==hardware_lab0_axi_gpio_0_1 || ORIG_REF_NAME==hardware_lab0_axi_gpio_0_1}] {/U0 }]/U0 ]]

# XDC: bd/hardware_lab0/ip/hardware_lab0_rst_processing_system7_0_100M_1/hardware_lab0_rst_processing_system7_0_100M_1_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hardware_lab0_rst_processing_system7_0_100M_1 || ORIG_REF_NAME==hardware_lab0_rst_processing_system7_0_100M_1}]

# XDC: bd/hardware_lab0/ip/hardware_lab0_rst_processing_system7_0_100M_1/hardware_lab0_rst_processing_system7_0_100M_1.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hardware_lab0_rst_processing_system7_0_100M_1 || ORIG_REF_NAME==hardware_lab0_rst_processing_system7_0_100M_1}]

# XDC: bd/hardware_lab0/ip/hardware_lab0_rst_processing_system7_0_100M_1/hardware_lab0_rst_processing_system7_0_100M_1_ooc.xdc

# XDC: bd/hardware_lab0/ip/hardware_lab0_xbar_1/hardware_lab0_xbar_1_ooc.xdc

# XDC: bd/hardware_lab0/ip/hardware_lab0_auto_pc_0/hardware_lab0_auto_pc_0_ooc.xdc

# XDC: bd/hardware_lab0/hardware_lab0_ooc.xdc
