# 
# Synthesis run script generated by Vivado
# 

set_param gui.test TreeTableDev
debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000

create_project -in_memory -part xc7z010clg400-1
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/erick.medina/Documents/ESDC/LAB0/lab0/lab0.cache/wt [current_project]
set_property parent.project_path C:/Users/erick.medina/Documents/ESDC/LAB0/lab0/lab0.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part digilentinc.com:zybo:part0:1.0 [current_project]
add_files C:/Users/erick.medina/Documents/ESDC/LAB0/lab0/lab0.srcs/sources_1/bd/hardware_lab0/hardware_lab0.bd
set_property used_in_implementation false [get_files -all c:/Users/erick.medina/Documents/ESDC/LAB0/lab0/lab0.srcs/sources_1/bd/hardware_lab0/ip/hardware_lab0_processing_system7_0_0/hardware_lab0_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/erick.medina/Documents/ESDC/LAB0/lab0/lab0.srcs/sources_1/bd/hardware_lab0/ip/hardware_lab0_axi_gpio_1_0/hardware_lab0_axi_gpio_1_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/erick.medina/Documents/ESDC/LAB0/lab0/lab0.srcs/sources_1/bd/hardware_lab0/ip/hardware_lab0_axi_gpio_1_0/hardware_lab0_axi_gpio_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/erick.medina/Documents/ESDC/LAB0/lab0/lab0.srcs/sources_1/bd/hardware_lab0/ip/hardware_lab0_axi_gpio_1_0/hardware_lab0_axi_gpio_1_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/erick.medina/Documents/ESDC/LAB0/lab0/lab0.srcs/sources_1/bd/hardware_lab0/ip/hardware_lab0_axi_gpio_2_0/hardware_lab0_axi_gpio_2_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/erick.medina/Documents/ESDC/LAB0/lab0/lab0.srcs/sources_1/bd/hardware_lab0/ip/hardware_lab0_axi_gpio_2_0/hardware_lab0_axi_gpio_2_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/erick.medina/Documents/ESDC/LAB0/lab0/lab0.srcs/sources_1/bd/hardware_lab0/ip/hardware_lab0_axi_gpio_2_0/hardware_lab0_axi_gpio_2_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/erick.medina/Documents/ESDC/LAB0/lab0/lab0.srcs/sources_1/bd/hardware_lab0/ip/hardware_lab0_axi_gpio_0_1/hardware_lab0_axi_gpio_0_1_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/erick.medina/Documents/ESDC/LAB0/lab0/lab0.srcs/sources_1/bd/hardware_lab0/ip/hardware_lab0_axi_gpio_0_1/hardware_lab0_axi_gpio_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/erick.medina/Documents/ESDC/LAB0/lab0/lab0.srcs/sources_1/bd/hardware_lab0/ip/hardware_lab0_axi_gpio_0_1/hardware_lab0_axi_gpio_0_1.xdc]
set_property used_in_implementation false [get_files -all c:/Users/erick.medina/Documents/ESDC/LAB0/lab0/lab0.srcs/sources_1/bd/hardware_lab0/ip/hardware_lab0_rst_processing_system7_0_100M_1/hardware_lab0_rst_processing_system7_0_100M_1_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/erick.medina/Documents/ESDC/LAB0/lab0/lab0.srcs/sources_1/bd/hardware_lab0/ip/hardware_lab0_rst_processing_system7_0_100M_1/hardware_lab0_rst_processing_system7_0_100M_1.xdc]
set_property used_in_implementation false [get_files -all c:/Users/erick.medina/Documents/ESDC/LAB0/lab0/lab0.srcs/sources_1/bd/hardware_lab0/ip/hardware_lab0_rst_processing_system7_0_100M_1/hardware_lab0_rst_processing_system7_0_100M_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/erick.medina/Documents/ESDC/LAB0/lab0/lab0.srcs/sources_1/bd/hardware_lab0/ip/hardware_lab0_xbar_1/hardware_lab0_xbar_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/erick.medina/Documents/ESDC/LAB0/lab0/lab0.srcs/sources_1/bd/hardware_lab0/ip/hardware_lab0_auto_pc_0/hardware_lab0_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all C:/Users/erick.medina/Documents/ESDC/LAB0/lab0/lab0.srcs/sources_1/bd/hardware_lab0/hardware_lab0_ooc.xdc]
set_property is_locked true [get_files C:/Users/erick.medina/Documents/ESDC/LAB0/lab0/lab0.srcs/sources_1/bd/hardware_lab0/hardware_lab0.bd]

read_vhdl -library xil_defaultlib C:/Users/erick.medina/Documents/ESDC/LAB0/lab0/lab0.srcs/sources_1/bd/hardware_lab0/hdl/hardware_lab0_wrapper.vhd
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
catch { write_hwdef -file hardware_lab0_wrapper.hwdef }
synth_design -top hardware_lab0_wrapper -part xc7z010clg400-1
write_checkpoint hardware_lab0_wrapper.dcp
catch { report_utilization -file hardware_lab0_wrapper_utilization_synth.rpt -pb hardware_lab0_wrapper_utilization_synth.pb }
