# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/lab1_extra/lab1_extra.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab1_extra || ORIG_REF_NAME==lab1_extra}]

# IP: bd/lab1_extra/ip/lab1_extra_processing_system7_0_0/lab1_extra_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab1_extra_processing_system7_0_0 || ORIG_REF_NAME==lab1_extra_processing_system7_0_0}]

# IP: bd/lab1_extra/ip/lab1_extra_axi_gpio_0_0/lab1_extra_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab1_extra_axi_gpio_0_0 || ORIG_REF_NAME==lab1_extra_axi_gpio_0_0}]

# IP: bd/lab1_extra/ip/lab1_extra_axi_gpio_0_1/lab1_extra_axi_gpio_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab1_extra_axi_gpio_0_1 || ORIG_REF_NAME==lab1_extra_axi_gpio_0_1}]

# IP: bd/lab1_extra/ip/lab1_extra_processing_system7_0_axi_periph_0/lab1_extra_processing_system7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab1_extra_processing_system7_0_axi_periph_0 || ORIG_REF_NAME==lab1_extra_processing_system7_0_axi_periph_0}]

# IP: bd/lab1_extra/ip/lab1_extra_rst_processing_system7_0_100M_0/lab1_extra_rst_processing_system7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab1_extra_rst_processing_system7_0_100M_0 || ORIG_REF_NAME==lab1_extra_rst_processing_system7_0_100M_0}]

# IP: bd/lab1_extra/ip/lab1_extra_xbar_0/lab1_extra_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab1_extra_xbar_0 || ORIG_REF_NAME==lab1_extra_xbar_0}]

# IP: bd/lab1_extra/ip/lab1_extra_VGA_SYNC_0_0/lab1_extra_VGA_SYNC_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab1_extra_VGA_SYNC_0_0 || ORIG_REF_NAME==lab1_extra_VGA_SYNC_0_0}]

# IP: bd/lab1_extra/ip/lab1_extra_blk_mem_gen_0_0/lab1_extra_blk_mem_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab1_extra_blk_mem_gen_0_0 || ORIG_REF_NAME==lab1_extra_blk_mem_gen_0_0}]

# IP: bd/lab1_extra/ip/lab1_extra_session4_0_0/lab1_extra_session4_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab1_extra_session4_0_0 || ORIG_REF_NAME==lab1_extra_session4_0_0}]

# IP: bd/lab1_extra/ip/lab1_extra_add_generator_0_1/lab1_extra_add_generator_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab1_extra_add_generator_0_1 || ORIG_REF_NAME==lab1_extra_add_generator_0_1}]

# IP: bd/lab1_extra/ip/lab1_extra_auto_pc_0/lab1_extra_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab1_extra_auto_pc_0 || ORIG_REF_NAME==lab1_extra_auto_pc_0}]

# XDC: bd/lab1_extra/ip/lab1_extra_processing_system7_0_0/lab1_extra_processing_system7_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==lab1_extra_processing_system7_0_0 || ORIG_REF_NAME==lab1_extra_processing_system7_0_0}] {/inst }]/inst ]]

# XDC: bd/lab1_extra/ip/lab1_extra_axi_gpio_0_0/lab1_extra_axi_gpio_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==lab1_extra_axi_gpio_0_0 || ORIG_REF_NAME==lab1_extra_axi_gpio_0_0}] {/U0 }]/U0 ]]

# XDC: bd/lab1_extra/ip/lab1_extra_axi_gpio_0_0/lab1_extra_axi_gpio_0_0_ooc.xdc

# XDC: bd/lab1_extra/ip/lab1_extra_axi_gpio_0_0/lab1_extra_axi_gpio_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==lab1_extra_axi_gpio_0_0 || ORIG_REF_NAME==lab1_extra_axi_gpio_0_0}] {/U0 }]/U0 ]]

# XDC: bd/lab1_extra/ip/lab1_extra_axi_gpio_0_1/lab1_extra_axi_gpio_0_1_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==lab1_extra_axi_gpio_0_1 || ORIG_REF_NAME==lab1_extra_axi_gpio_0_1}] {/U0 }]/U0 ]]

# XDC: bd/lab1_extra/ip/lab1_extra_axi_gpio_0_1/lab1_extra_axi_gpio_0_1_ooc.xdc

# XDC: bd/lab1_extra/ip/lab1_extra_axi_gpio_0_1/lab1_extra_axi_gpio_0_1.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==lab1_extra_axi_gpio_0_1 || ORIG_REF_NAME==lab1_extra_axi_gpio_0_1}] {/U0 }]/U0 ]]

# XDC: bd/lab1_extra/ip/lab1_extra_rst_processing_system7_0_100M_0/lab1_extra_rst_processing_system7_0_100M_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab1_extra_rst_processing_system7_0_100M_0 || ORIG_REF_NAME==lab1_extra_rst_processing_system7_0_100M_0}]

# XDC: bd/lab1_extra/ip/lab1_extra_rst_processing_system7_0_100M_0/lab1_extra_rst_processing_system7_0_100M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab1_extra_rst_processing_system7_0_100M_0 || ORIG_REF_NAME==lab1_extra_rst_processing_system7_0_100M_0}]

# XDC: bd/lab1_extra/ip/lab1_extra_rst_processing_system7_0_100M_0/lab1_extra_rst_processing_system7_0_100M_0_ooc.xdc

# XDC: bd/lab1_extra/ip/lab1_extra_xbar_0/lab1_extra_xbar_0_ooc.xdc

# XDC: bd/lab1_extra/ip/lab1_extra_blk_mem_gen_0_0/lab1_extra_blk_mem_gen_0_0_ooc.xdc

# XDC: bd/lab1_extra/ip/lab1_extra_auto_pc_0/lab1_extra_auto_pc_0_ooc.xdc

# XDC: bd/lab1_extra/lab1_extra_ooc.xdc
